# Generated by Django 4.1.13 on 2025-01-25 14:27

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_FlatSchedule',
            fields=[
                ('_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('BaseParameters', djongo.models.fields.ArrayField(max_length=1, model_container=api.models.Model_FlatScheduleParameters)),
                ('BaseSchedules', djongo.models.fields.ArrayField(max_length=1, model_container=api.models.Model_FlatScheduleBase)),
                ('CurrentSchedules', djongo.models.fields.ArrayField(max_length=1, model_container=api.models.Model_FlatScheduleDetailed)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collection_schedule_main',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Model_FlatScheduleBase',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nameList', djongo.models.fields.ArrayField(model_container=api.models.Model_IntString)),
                ('scheduleName', djongo.models.fields.ArrayField(model_container=api.models.Model_IntArray)),
                ('scheduleDay', djongo.models.fields.ArrayField(model_container=api.models.Model_IntArray)),
                ('scheduleGroup', djongo.models.fields.ArrayField(model_container=api.models.Model_IntArray)),
                ('scheduleLesson', djongo.models.fields.ArrayField(model_container=api.models.Model_IntIntIntArrayArray)),
                ('cabinetLesson', djongo.models.fields.ArrayField(model_container=api.models.Model_IntIntIntArrayArray)),
                ('teacherLesson', djongo.models.fields.ArrayField(model_container=api.models.Model_IntIntIntArrayArray)),
            ],
            options={
                'ordering': ['-_id'],
            },
        ),
        migrations.CreateModel(
            name='Model_FlatScheduleDetailed',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scheduleDay', djongo.models.fields.ArrayField(model_container=api.models.Model_IntArray)),
                ('scheduleGroup', djongo.models.fields.ArrayField(model_container=api.models.Model_IntArray)),
                ('scheduleLesson', djongo.models.fields.ArrayField(model_container=api.models.Model_IntIntIntArrayArray)),
                ('cabinetLesson', djongo.models.fields.ArrayField(model_container=api.models.Model_IntIntIntArrayArray)),
                ('teacherLesson', djongo.models.fields.ArrayField(model_container=api.models.Model_IntIntIntArrayArray)),
                ('version', models.IntegerField()),
            ],
            options={
                'ordering': ['-_id'],
            },
        ),
        migrations.CreateModel(
            name='Model_FlatScheduleParameters',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cabinetList', djongo.models.fields.ArrayField(model_container=api.models.Model_IntString)),
                ('groupList', djongo.models.fields.ArrayField(model_container=api.models.Model_IntString)),
                ('lessonList', djongo.models.fields.ArrayField(model_container=api.models.Model_IntString)),
                ('teacherList', djongo.models.fields.ArrayField(model_container=api.models.Model_IntString)),
                ('dayList', djongo.models.fields.ArrayField(model_container=api.models.Model_IntDate)),
            ],
            options={
                'ordering': ['-_id'],
            },
        ),
        migrations.CreateModel(
            name='Model_IntArray',
            fields=[
                ('specialId', models.IntegerField(primary_key=True, serialize=False)),
                ('scheduleId', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
            options={
                'ordering': ['-specialId'],
            },
        ),
        migrations.CreateModel(
            name='Model_IntDate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Model_IntIntIntArrayArray',
            fields=[
                ('specialId', models.IntegerField(primary_key=True, serialize=False)),
                ('scheduleId', models.IntegerField()),
                ('pairNum', models.IntegerField()),
                ('subPairs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('subGroups', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
            options={
                'ordering': ['-specialId'],
            },
        ),
        migrations.CreateModel(
            name='Model_IntString',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'someCollection',
                'ordering': ['-updated'],
            },
        ),
    ]
