from api.data import Data_IntString

APP_TYPEID_PARAMETERS_DISCIPLINE = 0
APP_TYPEID_PARAMETERS_TEACHER = 1
APP_TYPEID_PARAMETERS_GROUP = 2
APP_TYPEID_PARAMETERS_CABINET = 3
APP_TYPEID_PARAMETERS_DATE = 4

APP_PAIR_MAX_AMOUNT = 7

APP_TYPEID_IDENTIFIER_LIST = (
    Data_IntString(APP_TYPEID_PARAMETERS_DISCIPLINE, "lessonList"),
    Data_IntString(APP_TYPEID_PARAMETERS_TEACHER, "teacherList"),
    Data_IntString(APP_TYPEID_PARAMETERS_GROUP, "groupList"),
    Data_IntString(APP_TYPEID_PARAMETERS_CABINET, "cabinetList"),
    Data_IntString(APP_TYPEID_PARAMETERS_DATE, "dayList"),
)

MOBILE_APP_PAGE_COUNT = 15